import { Button } from "@/components/ui/button";
import { ArrowLeft, Code2, Download, ExternalLink, Play, RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const homeHref = import.meta.env.BASE_URL || "/";
const starterHtml = `<main class="card">\n  <span class="eyebrow">QUICK DEMO</span>\n  <h1>Hello from Code Lab</h1>\n  <p>Edit the HTML, CSS, or JavaScript and press Run demo.</p>\n  <button id="action">Try it</button>\n  <p id="result"></p>\n</main>`;
const starterCss = `:root { font-family: Inter, system-ui, sans-serif; color: #20323d; background: #eef3f5; }\nbody { min-height: 100vh; display: grid; place-items: center; margin: 0; }\n.card { width: min(520px, calc(100% - 40px)); padding: 40px; border: 1px solid #d5e0e4; border-radius: 24px; background: white; box-shadow: 0 18px 50px #18374618; }\n.eyebrow { color: #4c7b86; font-size: 11px; font-weight: 700; letter-spacing: .14em; }\nh1 { margin: 12px 0; }\nbutton { border: 0; border-radius: 10px; padding: 11px 16px; color: white; background: #294452; cursor: pointer; }`;
const starterJs = `document.querySelector('#action').addEventListener('click', () => {\n  document.querySelector('#result').textContent = 'It works.';\n});`;

export default function CodeLab() {
  const [, setLocation] = useLocation(); const [html, setHtml] = useState(starterHtml); const [css, setCss] = useState(starterCss); const [js, setJs] = useState(starterJs); const [run, setRun] = useState(0); const [message, setMessage] = useState("");
  const srcDoc = useMemo(() => `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style></head><body>${html}<script>${js.replace(/<\/script/gi, "<\\/script")}</script></body></html>`, [html, css, js, run]);
  const reset = () => { setHtml(starterHtml); setCss(starterCss); setJs(starterJs); setRun((value) => value + 1); setMessage("Starter demo restored."); };
  const exportHtml = () => { const blob = new Blob([srcDoc], { type: "text/html" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "agentforge-demo.html"; link.click(); URL.revokeObjectURL(url); setMessage("Downloaded agentforge-demo.html."); };
  return <div className="min-h-screen bg-[#f4f6f8] text-[#25313b]"><header className="border-b border-[#dfe5e9] bg-[#fbfcfd]"><div className="container flex h-20 items-center justify-between"><a href={homeHref} className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-[#1e3442] text-white">✦</span><span className="font-[Space_Grotesk] text-lg font-bold text-[#263b47]">AgentForge</span></a><button onClick={() => setLocation("/")} className="flex items-center gap-2 text-sm text-[#60737d] hover:text-[#294452]"><ArrowLeft className="size-4" /> Back to studio</button></div></header><main className="container py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[#597681]"><Code2 className="size-5" /><p className="text-xs font-bold uppercase tracking-[.16em]">Custom Code Lab</p></div><h1 className="mt-3 font-[Space_Grotesk] text-4xl font-semibold tracking-[-.04em] text-[#2e4651]">Build a quick demo.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#71818a]">Paste HTML, CSS, and JavaScript, run it safely in a sandboxed preview, then download the result as one HTML file.</p></div><div className="flex gap-2"><Button onClick={reset} variant="outline" className="rounded-lg border-[#d8e1e5] bg-white text-[#476572]"><RotateCcw className="mr-2 size-4" /> Reset</Button><Button onClick={exportHtml} variant="outline" className="rounded-lg border-[#d8e1e5] bg-white text-[#476572]"><Download className="mr-2 size-4" /> Export HTML</Button><Button onClick={() => { setRun((value) => value + 1); setMessage("Preview refreshed."); }} className="rounded-lg bg-[#294452] hover:bg-[#1f3540]"><Play className="mr-2 size-4" /> Run demo</Button></div></div><div className="mt-8 grid gap-5 xl:grid-cols-[1fr_1fr_1.1fr]"><Editor label="HTML" value={html} onChange={setHtml} /><Editor label="CSS" value={css} onChange={setCss} /><Editor label="JavaScript" value={js} onChange={setJs} /></div><section className="mt-6 overflow-hidden rounded-2xl border border-[#d8e3e7] bg-white shadow-[0_10px_28px_rgba(41,69,82,.06)]"><div className="flex items-center justify-between border-b border-[#e5eaed] px-5 py-3"><div><p className="text-sm font-semibold text-[#48616c]">Live preview</p><p className="text-xs text-[#97a3a9]">Sandboxed iframe · your code stays in this page</p></div><ExternalLink className="size-4 text-[#8da0a8]" /></div><iframe key={run} title="Code Lab preview" sandbox="allow-scripts" srcDoc={srcDoc} className="h-[430px] w-full bg-white" /></section>{message && <p className="mt-4 text-sm text-[#597681]">{message}</p>}</main></div>;
}
function Editor({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block overflow-hidden rounded-2xl border border-[#d8e3e7] bg-[#fbfcfd] shadow-[0_8px_22px_rgba(41,69,82,.04)]"><div className="border-b border-[#e5eaed] px-4 py-3 text-xs font-bold uppercase tracking-[.14em] text-[#597681]">{label}</div><textarea value={value} onChange={(event) => onChange(event.target.value)} spellCheck={false} className="h-[300px] w-full resize-y bg-[#fbfcfd] p-4 font-mono text-xs leading-5 text-[#425b66] outline-none" /></label>; }
