import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { generateAgentConfig } from "@/lib/offlineEngine";
import { addAgent, loadAgents, type LocalAgent } from "@/lib/localStore";
import { ArrowRight, Check, ChevronRight, Code2, Compass, Cpu, Download, Globe2, HardDrive, Layers3, Plus, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const examples = [
  "A patient study coach who helps me understand difficult topics and quizzes me without making me feel bad.",
  "A creative director who turns rough ideas into bold campaign concepts and gives honest feedback.",
  "A calm daily planner who helps me prioritize my life, remember what matters, and stay consistent.",
];
const accentClasses: Record<string, string> = { violet: "from-violet-500 to-fuchsia-500", cyan: "from-cyan-400 to-blue-500", amber: "from-amber-400 to-orange-500", rose: "from-rose-400 to-pink-600", emerald: "from-emerald-400 to-teal-600" };
const homeHref = import.meta.env.BASE_URL || "/";
const appBase = import.meta.env.BASE_URL || "/";
const logoSrc = `${import.meta.env.BASE_URL}agentforge-logo.png`;

export default function Home() {
  const [, setLocation] = useLocation();
  const [prompt, setPrompt] = useState("");
  const [savedAgents, setSavedAgents] = useState<LocalAgent[]>(() => loadAgents());

  const handleCreate = () => {
    const description = prompt.trim();
    if (!description) return;
    const agent = addAgent(generateAgentConfig(description));
    setSavedAgents(loadAgents());
    setLocation(`/agent/${agent.id}`);
  };

  return <div className="min-h-screen overflow-hidden bg-[#0a1117] text-[#e4edf0]">
    <header className="container flex h-20 items-center justify-between"><a href={homeHref} className="flex items-center gap-3"><img src={logoSrc} alt="Arphix" className="size-9 rounded-xl object-cover shadow-[0_8px_20px_rgba(0,0,0,.28)]" /><span className="font-[Space_Grotesk] text-lg font-bold tracking-tight">Arphix</span></a><nav className="hidden items-center gap-6 text-sm font-medium text-[#9eb0b7] md:flex"><a href="#how-it-works" className="hover:text-[#8bd3c7]">How it works</a><a href={`${appBase}code-lab`} className="flex items-center gap-1.5 hover:text-[#8bd3c7]"><Code2 className="size-3.5" /> Code Lab</a><a href={`${appBase}backup`} className="flex items-center gap-1.5 hover:text-[#8bd3c7]"><Download className="size-3.5" /> Backups</a><a href={`${appBase}tools`} className="flex items-center gap-1.5 hover:text-[#8bd3c7]"><Sparkles className="size-3.5" /> Tools</a></nav><span className="rounded-full border border-[#2c444d] bg-[#101d25] px-5 py-2 text-sm font-medium text-[#9eb0b7]">Offline-first</span></header>
    <main>
      <section className="container grid gap-16 pb-20 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-28 lg:pt-20"><div><Badge className="mb-6 rounded-full border border-[#2b515a] bg-[#142e38] px-4 py-2 text-xs font-semibold uppercase tracking-[.16em] text-[#8bd3c7] hover:bg-[#142e38]"><HardDrive className="mr-2 size-3.5" /> The private companion studio</Badge><h1 className="max-w-3xl font-[Space_Grotesk] text-5xl font-semibold leading-[1.03] tracking-[-.055em] text-[#e6eff2] sm:text-6xl lg:text-[5.35rem]">Make a companion that <span className="bg-gradient-to-r from-[#7bd2c4] via-[#c681d9] to-[#f0a77d] bg-clip-text text-transparent">stays on your device.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#a0b0b7]">Describe the role you want. AgentForge turns your words into a private workspace with a deterministic offline companion, local memory, saved notes, and browser-native tools.</p><div className="mt-9 flex flex-wrap items-center gap-3 text-sm text-[#9eb0b7]">{["No API keys", "No sign-in", "No database", "Saved in this browser"].map((item) => <span key={item} className="flex items-center gap-2"><span className="flex size-5 items-center justify-center rounded-full bg-[#12372e] text-[#8bd4b5]"><Check className="size-3" /></span>{item}</span>)}</div></div>
        <Card className="relative overflow-hidden rounded-[2rem] border-[#29424c] bg-[#101d25] p-5 shadow-[0_24px_70px_rgba(0,0,0,.28)] sm:p-7"><div className="absolute -right-16 -top-16 size-44 rounded-full bg-[#8bd3c7]/20 blur-2xl" /><div className="relative"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#7f939c]">Create your Arphix companion</p><p className="mt-1 text-sm text-[#9eb0b7]">Your private workspace stays on this device.</p></div><div className="flex size-10 items-center justify-center rounded-2xl bg-[#142d36] text-[#8bd3c7]"><WandSparkles className="size-5" /></div></div><Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="I want Arphix to help me..." className="min-h-[190px] resize-none rounded-2xl border-[#29424c] bg-[#0d171e] p-5 text-base leading-7 shadow-none placeholder:text-[#ada7bc] focus-visible:ring-[#8bd3c7]" /><div className="mt-4 flex flex-wrap gap-2">{examples.map((example, index) => <button key={example} onClick={() => setPrompt(example)} className="rounded-full border border-[#233840] bg-[#101d25] px-3 py-1.5 text-left text-xs text-[#91a4ab] hover:border-[#47717a] hover:bg-[#18343d]">Example {index + 1}</button>)}</div><Button onClick={handleCreate} disabled={!prompt.trim()} className="mt-5 h-12 w-full rounded-xl bg-[#173b45] text-sm font-semibold shadow-[0_10px_25px_rgba(48,34,95,.22)] hover:bg-[#225460]">Create Arphix<ArrowRight className="ml-2 size-4" /></Button><p className="mt-3 text-center text-xs leading-5 text-[#82979f]">No API key or account. Arphix uses a local model when available and a private offline fallback otherwise.</p></div></Card>
      </section>
      <section id="how-it-works" className="border-y border-[#223640] bg-[#101d25] py-20"><div className="container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8bd3c7]">Private by construction</p><h2 className="mt-3 font-[Space_Grotesk] text-3xl font-semibold tracking-[-.035em] text-[#e6eff2] sm:text-4xl">A static site with useful local tools, not a hidden service.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[{ icon: Compass, number: "01", title: "Describe the role", text: "A small local ruleset maps your description to a companion profile. There is no prompt sent to an LLM." }, { icon: Layers3, number: "02", title: "Keep context locally", text: "Notes, memories, settings, and conversations are stored only in this browser until you export them." }, { icon: Cpu, number: "03", title: "Work offline", text: "The workspace provides deterministic planning and reflection guidance plus browser-native voice and calculator tools." }].map(({ icon: Icon, number, title, text }) => <Card key={number} className="rounded-3xl border-[#223640] bg-[#0d171e] p-7 shadow-none"><div className="flex items-center justify-between"><div className="flex size-11 items-center justify-center rounded-2xl bg-[#142e38] text-[#8bd3c7]"><Icon className="size-5" /></div><span className="font-[Space_Grotesk] text-sm font-semibold text-[#71858f]">{number}</span></div><h3 className="mt-8 font-[Space_Grotesk] text-xl font-semibold text-[#d9e6ea]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#95a7ae]">{text}</p></Card>)}</div></div></section>
      <section id="features" className="container py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8bd3c7]">Portable by default</p><h2 className="mt-3 font-[Space_Grotesk] text-3xl font-semibold tracking-[-.035em] text-[#e6eff2] sm:text-4xl">Everything stays under your control.</h2><p className="mt-5 max-w-md leading-7 text-[#95a7ae]">GitHub Pages can host this static application. There is no account system, server function, data store, or API credential to operate.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Local companion profiles", "Saved conversations", "Long-term memory", "Knowledge notes", "Voice input + read aloud", "Offline attachment notice", "Local calculator", "Portable JSON backups"].map((feature) => <div key={feature} className="flex items-center gap-3 rounded-2xl border border-[#223640] bg-[#101d25] px-4 py-4 shadow-[0_8px_24px_rgba(0,0,0,.18)]"><span className="flex size-7 items-center justify-center rounded-lg bg-[#142e38] text-[#8bd3c7]"><Check className="size-3.5" /></span><span className="text-sm font-medium text-[#a7b7bd]">{feature}</span></div>)}</div></div></section>
      <section className="container pb-20"><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><a href={`${appBase}tools`} className="group rounded-3xl border border-[#29424c] bg-gradient-to-br from-[#102a32] to-[#0d1b23] p-6 shadow-[0_15px_45px_rgba(0,0,0,.18)] transition hover:-translate-y-1 hover:border-[#47717a]"><div className="flex items-center justify-between"><div className="flex size-11 items-center justify-center rounded-xl bg-[#142e38] text-[#8bd3c7]"><Globe2 className="size-5" /></div><ArrowRight className="size-5 text-[#8bd3c7] transition group-hover:translate-x-1" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-[#8bd3c7]">Local tools</p><h2 className="mt-2 font-[Space_Grotesk] text-2xl font-semibold text-[#e4edf0]">Open the tools hub.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#9eb0b7]">Use Code Lab, backups, a local calculator, and a sandboxed browser workspace from one static application.</p></a><div className="rounded-3xl border border-[#34535c] bg-[#0d1b23] p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#142e38] text-[#8bd3c7]"><ShieldCheck className="size-5" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-[#8bd3c7]">Clear limitation</p><h2 className="mt-2 font-[Space_Grotesk] text-2xl font-semibold text-[#e4edf0]">Offline is not a hosted AI model.</h2><p className="mt-2 text-sm leading-6 text-[#9eb0b7]">AgentForge now offers deterministic, privacy-first guidance. It does not present generated model output as if it came from an API or an autonomous model.</p></div></div></section>
      {savedAgents.length > 0 && <section className="container pb-24"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8bd3c7]">Your local studio</p><h2 className="mt-2 font-[Space_Grotesk] text-2xl font-semibold text-[#e6eff2]">Pick up where you left off.</h2></div><button onClick={() => document.querySelector("textarea")?.focus()} className="flex items-center gap-1 text-sm font-semibold text-[#8bd3c7]">Create another <Plus className="size-4" /></button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{savedAgents.map((agent) => <button key={agent.id} onClick={() => setLocation(`/agent/${agent.id}`)} className="group rounded-3xl border border-[#223640] bg-[#101d25] p-5 text-left shadow-[0_8px_28px_rgba(0,0,0,.2)] transition hover:-translate-y-1 hover:border-[#476f78]"><div className={`flex size-12 items-center justify-center rounded-2xl bg-gradient-to-br text-xl text-white ${accentClasses[agent.accent] || accentClasses.violet}`}>{agent.icon}</div><div className="mt-5 flex items-center justify-between"><h3 className="font-[Space_Grotesk] text-lg font-semibold text-[#e4edf0]">{agent.name}</h3><ChevronRight className="size-4 text-[#71858f] transition group-hover:translate-x-1" /></div><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#95a7ae]">{agent.tagline}</p></button>)}</div></section>}
    </main><footer className="border-t border-[#223640] bg-[#101d25] py-8"><div className="container flex flex-col justify-between gap-3 text-sm text-[#6f828b] sm:flex-row"><span>AgentForge · Private tools, local data.</span><span>Static GitHub Pages-ready build.</span></div></footer>
  </div>;
}
